import { http, HttpResponse, delay } from 'msw'
import { mockUser } from '../data'

let accessToken = 'mock-access-token-' + Date.now()

export const authHandlers = [
  // CSRF cookie — always succeed in mock/dev mode
  http.get('/api/sanctum/csrf-cookie', async () => {
    await delay(100)
    return HttpResponse.json({ message: 'CSRF cookie set' }, {
      status: 200,
      headers: { 'Set-Cookie': 'XSRF-TOKEN=mock-xsrf-token; Path=/' },
    })
  }),

  // Also catch the variant without /api prefix (used when baseURL is stripped)
  http.get('/sanctum/csrf-cookie', async () => {
    await delay(100)
    return HttpResponse.json({ message: 'CSRF cookie set' }, {
      status: 200,
      headers: { 'Set-Cookie': 'XSRF-TOKEN=mock-xsrf-token; Path=/' },
    })
  }),

  http.post('/api/auth/register', async ({ request }) => {
    await delay(800)
    const body = await request.json() as Record<string, string>
    return HttpResponse.json({ message: 'OTP sent', identifier: body.phone || body.email }, { status: 200 })
  }),

  http.post('/api/auth/verify-otp', async ({ request }) => {
    await delay(600)
    const body = await request.json() as Record<string, string>
    // Accept any 4-digit numeric code in mock/dev mode (generated by our dev email service)
    if (!body.otp || !/^\d{4}$/.test(body.otp)) {
      return HttpResponse.json({ message: 'Invalid OTP' }, { status: 400 })
    }
    accessToken = 'mock-access-token-' + Date.now()
    return HttpResponse.json({ accessToken, user: mockUser }, { status: 200 })
  }),

  http.post('/api/auth/resend-otp', async ({ request }) => {
    await delay(400)
    const body = await request.json() as Record<string, string>
    return HttpResponse.json({ message: 'OTP resent', identifier: body.identifier }, { status: 200 })
  }),

  http.post('/api/auth/login', async () => {
    await delay(800)
    accessToken = 'mock-access-token-' + Date.now()
    return HttpResponse.json({ accessToken, user: mockUser }, { status: 200 })
  }),

  http.post('/api/auth/refresh', async () => {
    await delay(300)
    accessToken = 'mock-access-token-' + Date.now()
    return HttpResponse.json({ accessToken }, { status: 200 })
  }),

  http.post('/api/auth/logout', async () => {
    await delay(200)
    return HttpResponse.json({ message: 'Logged out' }, { status: 200 })
  }),

  http.post('/api/auth/pin/set', async () => {
    await delay(400)
    return HttpResponse.json({ message: 'PIN created' }, { status: 200 })
  }),

  http.post('/api/auth/pin/verify', async () => {
    await delay(400)
    return HttpResponse.json({ message: 'PIN verified' }, { status: 200 })
  }),

  http.get('/api/users/me', async () => {
    await delay(300)
    return HttpResponse.json(mockUser)
  }),
]